os: linux
language: generic
dist: focal
jobs:
  include:
    - name: "Python 3.6"
      before_install:
        - pyenv versions
        - pyenv install --list
        - pyenv global 3.6.10
    - name: "Python 3.7"
      before_install:
        - pyenv global 3.7.6
    - name: "Python 3.8"
      before_install:
        - pyenv global 3.8.1
cache:
  directories:
    - $HOME/.cache/pip
    - node_modules
env:
  - DJANGO_SETTINGS_MODULE="babybuddy.settings.travis"
install:
  - nvm use 12
  - npm install -g gulp-cli
  - npm install
  - pip install pipenv
  - pipenv install --dev
before_script:
  - gulp lint
script:
  - gulp coverage
after_success:
  - pipenv run coveralls
notifications:
  email: false
