sudo: false
dist: xenial
language: python
cache:
    pip: true
    directories:
        - node_modules
python:
    - 3.6
    - 3.7
    - 3.8
env:
    - DJANGO_SETTINGS_MODULE="babybuddy.settings.travis"
install:
    - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install 8
    - npm install -g gulp-cli && npm install
    - pip install pipenv && pipenv install --dev
before_script:
    - gulp lint
script:
    - gulp coverage
after_success:
    - pipenv run coveralls
notifications:
    email: false
