extra_css:
  - css/extras.css
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
nav:
  - "index.md"
  - "Setup":
      - "setup/deployment.md"
      - "setup/ssl.md"
      - "setup/subdirectory.md"
      - "setup/proxy.md"
  - "Configuration":
      - "configuration/intro.md"
      - "configuration/application.md"
      - "configuration/database.md"
      - "configuration/email.md"
      - "configuration/homeassistant.md"
      - "configuration/security.md"
      - "configuration/storage.md"
  - "User Guide":
      - "user-guide/getting-started.md"
      - "user-guide/managing-users.md"
      - "user-guide/adding-entries.md"
      - "user-guide/using-timers.md"
  - "Contributing":
      - "contributing/development-environment.md"
      - "contributing/translation.md"
      - "contributing/pull-requests.md"
      - "contributing/gulp-command-reference.md"
  - "import-export.md"
  - "api.md"
theme:
  name: material
  favicon: assets/images/favicon.svg
  features:
    - navigation.expand
    - navigation.instant
    - navigation.tracking
    - search.share
    - search.suggest
  logo: assets/images/logo.svg
  palette:
    scheme: slate
repo_name: babybuddy/babybuddy
repo_url: https://github.com/babybuddy/babybuddy
site_name: Baby Buddy Documentation
site_url: https://docs.baby-buddy.net
